INSERT INTO guide_table(guide_id,guide_teacher,guide_student)VALUES('0','MENTOR','MENTOR');
INSERT INTO guide_table(guide_teacher,guide_student)VALUES('ACHYUTANANDA PARIDA','SUVAM SAHOO');
INSERT INTO guide_table(guide_teacher,guide_student)VALUES('AJAY KUMAR BHURJEE','RAJU KUMAR'); 
INSERT INTO guide_table(guide_teacher,guide_student)VALUES('ALOK PATRA','AKASH RANJAN'); 
INSERT INTO guide_table(guide_teacher,guide_student)VALUES('ARTTATRAN SAHU','SWETA BEHERA'); 
INSERT INTO guide_table(guide_teacher,guide_student)VALUES('ARUNIMA PATTANAYAK','VIVEK'); 
INSERT INTO guide_table(guide_teacher,guide_student)VALUES('BASANT KUMAR SAHU','SHRAVAN'); 
INSERT INTO guide_table(guide_teacher,guide_student)VALUES('BHASKAR BHAULA','NISHANT'); 
INSERT INTO guide_table(guide_teacher,guide_student)VALUES('DEBASISH CHOWDHURY','SUBHASMITA'); 
INSERT INTO guide_table(guide_teacher,guide_student)VALUES('DEEPAK ACHARYA','RAJESH'); 
INSERT INTO guide_table(guide_teacher,guide_student)VALUES('DEEPANJALI MISRA','PRIYANKA PATRO'); 
INSERT INTO guide_table(guide_teacher,guide_student)VALUES('G. VIVEKANANDA','AMRUTA'); 
INSERT INTO guide_table(guide_teacher,guide_student)VALUES('G. GIRISH','PARTH'); 
INSERT INTO guide_table(guide_teacher,guide_student)VALUES('GAYATRI PA NDA','MANOJ BARIK'); 
INSERT INTO guide_table(guide_teacher,guide_student)VALUES('MANOJ KAR','DEBADATTA'); 
INSERT INTO guide_table(guide_teacher,guide_student)VALUES('MANISHA CHHOTRAY','SIMRAN'); 
INSERT INTO guide_table(guide_teacher,guide_student)VALUES('MITU BARAL','PRANAY'); 
INSERT INTO guide_table(guide_teacher,guide_student)VALUES('MONALISA MISRA','DEVASHISH'); 
INSERT INTO guide_table(guide_teacher,guide_student)VALUES('MOTAHAR REZA','AVINASH PATRA'); 
INSERT INTO guide_table(guide_teacher,guide_student)VALUES('NAGEN  BHUSHAN PATANAIK','DAYANAND'); 
INSERT INTO guide_table(guide_teacher,guide_student)VALUES('NAYANIKA MAHAPATRA','SWATI'); 
INSERT INTO guide_table(guide_teacher,guide_student)VALUES('RASHMITA JENA','DIPU'); 
INSERT INTO guide_table(guide_teacher,guide_student)VALUES('PALASH DAS','AMRITA'); 
INSERT INTO guide_table(guide_teacher,guide_student)VALUES('PARTHA PRATIM DAS','AJAY KUMAR KHETAN'); 
INSERT INTO guide_table(guide_teacher,guide_student)VALUES('PRANEETHKUMR PEDAPATI','AKANKSHA'); 
INSERT INTO guide_table(guide_teacher,guide_student)VALUES('PRASUN DUTTA','AVINASH MAHALA'); 
INSERT INTO guide_table(guide_teacher,guide_student)VALUES('RAJA RAJESWARI','MEERINA'); 
INSERT INTO guide_table(guide_teacher,guide_student)VALUES('RANJAN KUMAR PADHI','MANOJ SWAIN'); 
INSERT INTO guide_table(guide_teacher,guide_student)VALUES('BIBHUTI BHUSAN MISHRA','NIHAL'); 
INSERT INTO guide_table(guide_teacher,guide_student)VALUES('SANDIPAN MALLIK','SACHIN'); 
INSERT INTO guide_table(guide_teacher,guide_student)VALUES('SARITA SAHU','VISHAKHA'); 
INSERT INTO guide_table(guide_teacher,guide_student)VALUES('SASMITA PADHI','SASWATI PANDA'); 
INSERT INTO guide_table(guide_teacher,guide_student)VALUES('SHRABANI MAHATA','SHALINI'); 
INSERT INTO guide_table(guide_teacher,guide_student)VALUES('SIBARAMA PANIGRAHI','CHANDA'); 
INSERT INTO guide_table(guide_teacher,guide_student)VALUES('SOUMYA SAMANTA','DEVYANI'); 
INSERT INTO guide_table(guide_teacher,guide_student)VALUES('SREEKUAMR CH','SUBHANKAR'); 
INSERT INTO guide_table(guide_teacher,guide_student)VALUES('SRETA PATANAIK','SONALI SAHU'); 
INSERT INTO guide_table(guide_teacher,guide_student)VALUES('SRINIVAS ROULA','DEBADEEPA'); 
INSERT INTO guide_table(guide_teacher,guide_student)VALUES('SUMANTA KUMAR PATNAIK','RAHUL PANDA'); 
INSERT INTO guide_table(guide_teacher,guide_student)VALUES('SWATI DORA','SHAYANKI'); 
INSERT INTO guide_table(guide_teacher,guide_student)VALUES('TAPAS BAYAN','SHEETAL'); 
INSERT INTO guide_table(guide_teacher,guide_student)VALUES('A B MANDAL','AMIT'); 
INSERT INTO guide_table(guide_teacher,guide_student)VALUES('PRASHANT MAHANTY','RADHAKRISHNA'); 
INSERT INTO guide_table(guide_teacher,guide_student)VALUES('SURYAMANI','MANISHA PANDA'); 
INSERT INTO guide_table(guide_teacher,guide_student)VALUES('ARNAB BANERJEE','PANCHAM'); 
INSERT INTO guide_table(guide_teacher,guide_student)VALUES('RAMKULESH THAKUR','DEEPAK'); 
INSERT INTO guide_table(guide_teacher,guide_student)VALUES('SUJATA MUDALI','SINDHU'); 
INSERT INTO guide_table(guide_teacher,guide_student)VALUES('RABI CHANDRA SINGH','PRAPTI'); 
INSERT INTO guide_table(guide_teacher,guide_student)VALUES('RAJENDRA KUMAR KAHADANGA','SAURAV'); 
